// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AgregarproductoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void agregarproducto() {
    driver.Navigate().GoToUrl("https://www.amazon.com/-/es/ref=nav_logo");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".a-section > .a-section:nth-child(1) > .a-link-normal .\\_quad-category-card_style_fluidLandscapeImage__3eTVC")).Click();
    driver.FindElement(By.CssSelector(".\\_featured-brands-search-top-desktop_Grid_grid-column-desktop__Rdvlk:nth-child(1) .\\_featured-brands-search-top-desktop_Category_category-image__2hyh0")).Click();
    js.ExecuteScript("window.scrollTo(0,400)");
    js.ExecuteScript("window.scrollTo(0,1099)");
    {
      var element = driver.FindElement(By.CssSelector(".ProductGridItem__itemOuter__KUtvv:nth-child(4) > div > .Overlay__overlay__LloCU"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".ProductGridItem__itemOuter__KUtvv:nth-child(2) .Button__button__b_aG7")).Click();
    driver.FindElement(By.CssSelector(".ProductGridItem__itemOuter__KUtvv:nth-child(3) .Button__button__b_aG7")).Click();
    driver.FindElement(By.CssSelector("#nav-cart-text-container > .nav-line-2")).Click();
    {
      var element = driver.FindElement(By.Id("nav-orders"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("#nav-orders > .nav-line-2"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector("#nav-cart-text-container > .nav-line-2")).Click();
  }
}
